//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absence
    {
        public int AbsenceID { get; set; }
        public System.DateTime AbsenceDate { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<int> RegEmpLate { get; set; }
        public Nullable<int> RegEmpOut { get; set; }
        public Nullable<int> RegEmpLeftEarly { get; set; }
        public Nullable<int> TempEmpOut { get; set; }
        public Nullable<int> TempEmpLate { get; set; }
        public Nullable<int> TempEmpLeftEarly { get; set; }
        public Nullable<int> InmateLeftEarly { get; set; }
        public Nullable<int> InmateOut { get; set; }
        public Nullable<int> EmployeesOnVacation { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
