//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_Groups
    {
        public AD_Groups()
        {
            this.AD_Products = new HashSet<AD_Products>();
        }
    
        public int AD_GroupId { get; set; }
        public string AD_GroupName { get; set; }
    
        public virtual ICollection<AD_Products> AD_Products { get; set; }
    }
}
