//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_Products
    {
        public AD_Products()
        {
            this.AD_WeekData = new HashSet<AD_WeekData>();
        }
    
        public int AD_ProductID { get; set; }
        public int AD_GroupID { get; set; }
        public string AD_ProductName { get; set; }
        public int AD_SubgroupId { get; set; }
    
        public virtual AD_Groups AD_Groups { get; set; }
        public virtual ICollection<AD_WeekData> AD_WeekData { get; set; }
    }
}
