//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_WeekData
    {
        public int AD_WeekDataID { get; set; }
        public int AD_ProductID { get; set; }
        public Nullable<int> AD_BudgetLbs { get; set; }
        public Nullable<int> AD_ActualLbs { get; set; }
        public Nullable<decimal> AD_BudgetDollars { get; set; }
        public Nullable<decimal> AD_ActualDollars { get; set; }
        public Nullable<System.DateTime> AD_WeekEnd { get; set; }
    
        public virtual AD_Products AD_Products { get; set; }
    }
}
