//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADAGIOSalesStatitic
    {
        public Nullable<System.DateTime> Date_2 { get; set; }
        public string Curr { get; set; }
        public Nullable<decimal> NetQtySold { get; set; }
        public Nullable<decimal> GrossSalesAmt { get; set; }
        public Nullable<decimal> GrossCreditAmt { get; set; }
        public Nullable<decimal> NetInvoiceAmt { get; set; }
        public Nullable<decimal> NetTaxes { get; set; }
        public Nullable<decimal> NetSalesAmt { get; set; }
        public Nullable<decimal> CostofSales { get; set; }
        public Nullable<int> InvoiceCount { get; set; }
        public Nullable<decimal> LargestInvoice { get; set; }
        public Nullable<decimal> SmallestInvoice { get; set; }
        public string LargestCustomer { get; set; }
        public string LargestSalesperson { get; set; }
        public Nullable<int> CNCount { get; set; }
        public Nullable<decimal> LargestCN { get; set; }
        public Nullable<decimal> SmallestCN { get; set; }
        public Nullable<System.DateTime> RateDate { get; set; }
        public Nullable<int> Rate { get; set; }
        public string RateRep { get; set; }
        public string DateMatching { get; set; }
        public string Filler { get; set; }
        public Nullable<int> RNumAS90ASTA { get; set; }
        public int StatsID { get; set; }
    }
}
