//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdagioItem
    {
        public Nullable<double> Item { get; set; }
        public Nullable<double> SetKey { get; set; }
        public Nullable<double> Item2 { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public Nullable<double> ReportGroup { get; set; }
        public Nullable<double> StockItem { get; set; }
        public Nullable<double> ItemsUsedinBOMCount { get; set; }
        public Nullable<double> SerialCount { get; set; }
        public Nullable<double> LayawayCounter { get; set; }
        public string Unit { get; set; }
        public string AltUnit1 { get; set; }
        public string AltUnit2 { get; set; }
        public string AltUnit3 { get; set; }
        public string AltUnit4 { get; set; }
        public string PurchaseUnit { get; set; }
        public string PriceUnit { get; set; }
        public Nullable<double> AltFactor1 { get; set; }
        public Nullable<double> AltFactor2 { get; set; }
        public Nullable<double> AltFactor3 { get; set; }
        public Nullable<double> AltFactor4 { get; set; }
        public Nullable<double> BasePrice { get; set; }
        public string PickingSeq { get; set; }
        public Nullable<double> StdCost { get; set; }
        public Nullable<double> UnitWeight { get; set; }
        public string SaleStartDate { get; set; }
        public string SaleEndDate { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public Nullable<double> CtrlAcctSet { get; set; }
        public Nullable<double> TaxStatus { get; set; }
        public Nullable<double> UserDefinedCost1 { get; set; }
        public Nullable<double> UserDefinedCost2 { get; set; }
        public string DiscType_T { get; set; }
        public string DiscFormat_T { get; set; }
        public string DiscBase_T { get; set; }
        public Nullable<double> DiscMarkupQty1 { get; set; }
        public Nullable<double> DiscMarkupQty2 { get; set; }
        public Nullable<double> DiscMarkupQty3 { get; set; }
        public Nullable<double> DiscMarkupQty4 { get; set; }
        public Nullable<double> DiscMarkupQty5 { get; set; }
        public Nullable<double> QtyonPO { get; set; }
        public Nullable<double> QtyonSO { get; set; }
        public Nullable<double> QtyTempCommitted { get; set; }
        public Nullable<double> QtyShippednotCost { get; set; }
        public Nullable<System.DateTime> LastShipmentDate { get; set; }
        public Nullable<System.DateTime> LastRcptDate { get; set; }
        public Nullable<double> MostRecentCost { get; set; }
        public Nullable<double> MarkupFactor { get; set; }
        public Nullable<System.DateTime> PrevPriceChangeDate { get; set; }
        public Nullable<double> PrevPrice { get; set; }
        public Nullable<System.DateTime> PrevStdCostDate { get; set; }
        public Nullable<double> PrevStdCost { get; set; }
        public Nullable<System.DateTime> PrevRecentCostDate { get; set; }
        public Nullable<double> PrevRecentCost { get; set; }
        public string Rcpt1 { get; set; }
        public string Rcpt2 { get; set; }
        public string Rcpt3 { get; set; }
        public string Rcpt4 { get; set; }
        public string Rcpt5 { get; set; }
        public string RcptDate1 { get; set; }
        public string RcptDate2 { get; set; }
        public string RcptDate3 { get; set; }
        public string RcptDate4 { get; set; }
        public string RcptDate5 { get; set; }
        public Nullable<double> QtyonHand1 { get; set; }
        public Nullable<double> QtyonHand2 { get; set; }
        public Nullable<double> QtyonHand3 { get; set; }
        public Nullable<double> QtyonHand4 { get; set; }
        public Nullable<double> QtyonHand5 { get; set; }
        public Nullable<double> TotalCost1 { get; set; }
        public Nullable<double> TotalCost2 { get; set; }
        public Nullable<double> TotalCost3 { get; set; }
        public Nullable<double> TotalCost4 { get; set; }
        public Nullable<double> TotalCost5 { get; set; }
        public Nullable<double> AvgDaysBetweenShipments { get; set; }
        public Nullable<double> AvgUnitsShipped { get; set; }
        public Nullable<double> ShipmentCount { get; set; }
        public Nullable<double> UnitsSoldPeriod1 { get; set; }
        public Nullable<double> UnitsSoldPeriod2 { get; set; }
        public Nullable<double> UnitsSoldPeriod3 { get; set; }
        public Nullable<double> UnitsSoldPeriod4 { get; set; }
        public Nullable<double> UnitsSoldPeriod5 { get; set; }
        public Nullable<double> UnitsSoldPeriod6 { get; set; }
        public Nullable<double> UnitsSoldPeriod7 { get; set; }
        public Nullable<double> UnitsSoldPeriod8 { get; set; }
        public Nullable<double> UnitsSoldPeriod9 { get; set; }
        public Nullable<double> UnitsSoldPeriod10 { get; set; }
        public Nullable<double> UnitsSoldPeriod11 { get; set; }
        public Nullable<double> UnitsSoldPeriod12 { get; set; }
        public Nullable<double> UnitsSoldPeriod13 { get; set; }
        public Nullable<double> UnitsSoldYTD { get; set; }
        public Nullable<double> UnitsSoldLY { get; set; }
        public Nullable<double> AmtSoldPeriod1 { get; set; }
        public Nullable<double> AmtSoldPeriod2 { get; set; }
        public Nullable<double> AmtSoldPeriod3 { get; set; }
        public Nullable<double> AmtSoldPeriod4 { get; set; }
        public Nullable<double> AmtSoldPeriod5 { get; set; }
        public Nullable<double> AmtSoldPeriod6 { get; set; }
        public Nullable<double> AmtSoldPeriod7 { get; set; }
        public Nullable<double> AmtSoldPeriod8 { get; set; }
        public Nullable<double> AmtSoldPeriod9 { get; set; }
        public Nullable<double> AmtSoldPeriod10 { get; set; }
        public Nullable<double> AmtSoldPeriod11 { get; set; }
        public Nullable<double> AmtSoldPeriod12 { get; set; }
        public Nullable<double> AmtSoldPeriod13 { get; set; }
        public Nullable<double> AmtSoldYTD { get; set; }
        public Nullable<double> AmtSoldLY { get; set; }
        public Nullable<double> TotalCostsPeriod1 { get; set; }
        public Nullable<double> TotalCostsPeriod2 { get; set; }
        public Nullable<double> TotalCostsPeriod3 { get; set; }
        public Nullable<double> TotalCostsPeriod4 { get; set; }
        public Nullable<double> TotalCostsPeriod5 { get; set; }
        public Nullable<double> TotalCostsPeriod6 { get; set; }
        public Nullable<double> TotalCostsPeriod7 { get; set; }
        public Nullable<double> TotalCostsPeriod8 { get; set; }
        public Nullable<double> TotalCostsPeriod9 { get; set; }
        public Nullable<double> TotalCostsPeriod10 { get; set; }
        public Nullable<double> TotalCostsPeriod11 { get; set; }
        public Nullable<double> TotalCostsPeriod12 { get; set; }
        public Nullable<double> TotalCostsPeriod13 { get; set; }
        public Nullable<double> TotalCostsYTD { get; set; }
        public Nullable<double> TotalCostsLY { get; set; }
        public Nullable<double> UnitsLostYTD { get; set; }
        public Nullable<double> UnitsLostLY { get; set; }
        public Nullable<double> DiscDecimals { get; set; }
        public Nullable<double> DiscMarkupAmt1 { get; set; }
        public Nullable<double> DiscMarkupAmt2 { get; set; }
        public Nullable<double> DiscMarkupAmt3 { get; set; }
        public Nullable<double> DiscMarkupAmt4 { get; set; }
        public Nullable<double> DiscMarkupAmt5 { get; set; }
        public Nullable<double> QtyOnHand { get; set; }
        public Nullable<double> Selected { get; set; }
        public string ActiveItem { get; set; }
        public string RNumAN81CITM { get; set; }
        public int ID { get; set; }
    }
}
