//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdagioOrderDetail
    {
        public string OrderKey { get; set; }
        public Nullable<double> Line { get; set; }
        public string DDocType_T { get; set; }
        public Nullable<double> DDoc { get; set; }
        public string LineType_T { get; set; }
        public Nullable<double> Item { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public string PickingSeq { get; set; }
        public string DiscLevel { get; set; }
        public string DCategory { get; set; }
        public string PriceUnit { get; set; }
        public Nullable<double> PriceOverride { get; set; }
        public Nullable<double> ExtensionOverride { get; set; }
        public Nullable<double> ReturntoInventory { get; set; }
        public Nullable<double> SerialCount { get; set; }
        public Nullable<double> TaxStatus { get; set; }
        public Nullable<double> Commissionable { get; set; }
        public Nullable<double> UnitFactor { get; set; }
        public Nullable<double> UnitWeight { get; set; }
        public Nullable<double> QtyOriginalOrdered { get; set; }
        public Nullable<double> QtyOrdered { get; set; }
        public Nullable<double> QtyShippedtoDate { get; set; }
        public Nullable<double> QtyShipped { get; set; }
        public Nullable<double> QtyBackordered { get; set; }
        public Nullable<double> ExtWeight { get; set; }
        public Nullable<double> ShipStockingUnits { get; set; }
        public Nullable<double> Loc { get; set; }
        public Nullable<double> Complete { get; set; }
        public string Curr { get; set; }
        public Nullable<double> Decimals { get; set; }
        public string PriceList { get; set; }
        public Nullable<double> OrderedInPO { get; set; }
        public Nullable<double> UnitDecimals { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> UnitCost { get; set; }
        public Nullable<double> ExtPrice { get; set; }
        public Nullable<double> ExtCost { get; set; }
        public Nullable<double> TaxAmt { get; set; }
        public Nullable<double> DTax1 { get; set; }
        public Nullable<double> DTax2 { get; set; }
        public Nullable<double> DTax3 { get; set; }
        public Nullable<double> DTax4 { get; set; }
        public Nullable<double> DTax5 { get; set; }
        public Nullable<double> DBase1 { get; set; }
        public Nullable<double> DBase2 { get; set; }
        public Nullable<double> DBase3 { get; set; }
        public Nullable<double> DBase4 { get; set; }
        public Nullable<double> DBase5 { get; set; }
        public Nullable<double> DiscAmt { get; set; }
        public Nullable<double> DiscExtension { get; set; }
        public Nullable<double> BasePrice { get; set; }
        public Nullable<double> ExtOrderPrice { get; set; }
        public Nullable<double> PriceFactor { get; set; }
        public string Serial1 { get; set; }
        public string Serial2 { get; set; }
        public string Serial3 { get; set; }
        public string Serial4 { get; set; }
        public string Serial5 { get; set; }
        public Nullable<System.DateTime> DExpectedShipDate { get; set; }
        public Nullable<double> MiscAmount { get; set; }
        public Nullable<double> MiscBasePrice { get; set; }
        public string MiscShortDescription { get; set; }
        public Nullable<double> MiscQuantity { get; set; }
        public string MiscFiller { get; set; }
        public string RNumAO80ALIN { get; set; }
        public int ID { get; set; }
    }
}
