//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adagio_N_ItemLocation
    {
        public int AppID { get; set; }
        public Nullable<int> Item { get; set; }
        public Nullable<short> Loc { get; set; }
        public Nullable<int> Item2 { get; set; }
        public string PickingSeq { get; set; }
        public Nullable<short> CarriedinLoc { get; set; }
        public Nullable<short> QtyonHandPlus { get; set; }
        public Nullable<short> QtyonPO { get; set; }
        public Nullable<short> QtyonSO { get; set; }
        public Nullable<short> QtyTempCommitted { get; set; }
        public Nullable<short> QtyShippednotCost { get; set; }
        public Nullable<short> RNumAN81CILO { get; set; }
    }
}
