//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bin
    {
        public Bin()
        {
            this.Feedings = new HashSet<Feeding>();
            this.BinDisbursements = new HashSet<BinDisbursement>();
            this.BinLoads = new HashSet<BinLoad>();
        }
    
        public int BinID { get; set; }
        public string BinName { get; set; }
        public Nullable<int> FarmID { get; set; }
        public Nullable<int> CurrentTicket { get; set; }
        public Nullable<int> CurrentPounds { get; set; }
        public Nullable<System.DateTime> LastDisbursement { get; set; }
        public Nullable<System.DateTime> LastLoaded { get; set; }
    
        public virtual Farm Farm { get; set; }
        public virtual ICollection<Feeding> Feedings { get; set; }
        public virtual ICollection<BinDisbursement> BinDisbursements { get; set; }
        public virtual ICollection<BinLoad> BinLoads { get; set; }
    }
}
