//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinDisbursement
    {
        public int BinDisbursementID { get; set; }
        public int BinID { get; set; }
        public int TicketNumber { get; set; }
        public int Pounds { get; set; }
        public string Note { get; set; }
        public Nullable<int> DisbursementType { get; set; }
        public System.DateTime DisbursementDate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> FeedID { get; set; }
        public int UserID { get; set; }
    
        public virtual DisbursementType DisbursementType1 { get; set; }
        public virtual Feeding Feeding { get; set; }
        public virtual Bin Bin { get; set; }
    }
}
