//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinFarm
    {
        public int BinFarmID { get; set; }
        public int BinID { get; set; }
        public int FarmID { get; set; }
    
        public virtual Bin Bin { get; set; }
        public virtual Farm Farm { get; set; }
    }
}
