//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinLoad
    {
        public int BinTicketID { get; set; }
        public int BinID { get; set; }
        public int TicketNumber { get; set; }
        public System.DateTime DateLoaded { get; set; }
        public int PoundsLoaded { get; set; }
        public string Vendor { get; set; }
        public string Note { get; set; }
    
        public virtual Bin Bin { get; set; }
    }
}
