//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentShipping
    {
        public int AppID { get; set; }
        public string CustomerName { get; set; }
        public string ItemDescription { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public Nullable<decimal> QuantityOnHand { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> ShippedAmount { get; set; }
        public Nullable<decimal> TodayUnits { get; set; }
    }
}
