//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentTotal
    {
        public int DepartmentTotalID { get; set; }
        public int DepartmentID { get; set; }
        public System.DateTime DTDate { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<int> DownTime { get; set; }
        public Nullable<decimal> ShiftWeight { get; set; }
        public Nullable<int> Absences { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
