//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementType
    {
        public DisbursementType()
        {
            this.BinDisbursements = new HashSet<BinDisbursement>();
        }
    
        public int DisbursementTypeID { get; set; }
        public string DisbursementTypeName { get; set; }
    
        public virtual ICollection<BinDisbursement> BinDisbursements { get; set; }
    }
}
