//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinishTime
    {
        public int FinishTimeID { get; set; }
        public System.DateTime FinishDateTime { get; set; }
        public int DepartmentID { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
