//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthStatus
    {
        public HealthStatus()
        {
            this.Ponds = new HashSet<Pond>();
        }
    
        public int HealthStatusId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Pond> Ponds { get; set; }
    }
}
