//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionTotal
    {
        public int ProductionTotalID { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public int PondId { get; set; }
        public Nullable<decimal> PlantWeight { get; set; }
        public Nullable<decimal> PondWeight { get; set; }
        public Nullable<decimal> WeighBacks { get; set; }
        public Nullable<decimal> AverageYield { get; set; }
    
        public virtual Pond Pond { get; set; }
    }
}
