//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.UserFarms = new HashSet<UserFarm>();
            this.Users = new HashSet<User>();
            this.Farms = new HashSet<Farm>();
            this.Ponds = new HashSet<Pond>();
        }
    
        public int StatusId { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<UserFarm> UserFarms { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Farm> Farms { get; set; }
        public virtual ICollection<Pond> Ponds { get; set; }
    }
}
