//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodaysProductionTotal
    {
        public int ProductionTotalID { get; set; }
        public Nullable<int> Station { get; set; }
        public Nullable<decimal> Nominal { get; set; }
        public Nullable<decimal> Weight { get; set; }
    }
}
