//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodaySampling
    {
        public int AppID { get; set; }
        public string code { get; set; }
        public string farmname { get; set; }
        public string shname { get; set; }
        public string pondname { get; set; }
        public Nullable<System.DateTime> regtime { get; set; }
        public string code2 { get; set; }
        public string codename { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<int> pondid { get; set; }
    }
}
