//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeighBack
    {
        public int WeightBackID { get; set; }
        public int PondID { get; set; }
        public System.DateTime WBDateTime { get; set; }
        public Nullable<decimal> Turtle { get; set; }
        public Nullable<decimal> Trash { get; set; }
        public Nullable<decimal> Shad { get; set; }
        public Nullable<decimal> Carp { get; set; }
        public Nullable<decimal> Bream { get; set; }
        public Nullable<decimal> LiveDisease { get; set; }
        public Nullable<decimal> DressedDisease { get; set; }
        public Nullable<decimal> DressedDiseasePct { get; set; }
        public Nullable<decimal> Backs { get; set; }
        public Nullable<decimal> RedFillet { get; set; }
        public Nullable<decimal> RedFilletPct { get; set; }
        public Nullable<decimal> BigFish { get; set; }
        public Nullable<decimal> DOAs { get; set; }
    
        public virtual Pond Pond { get; set; }
    }
}
