using SGApp.Models.Common;
using System;
namespace SGApp.DTOs
{
    public class Adagio_O_OrderHeaderDTO : IKey
    {

        public string Key { get; set; }
        public string CustPrefix { get; set; }
        public Nullable<short> Cust { get; set; }
        public string OrderKey { get; set; }
        public string DocType_T { get; set; }
        public Nullable<int> Doc { get; set; }
        public Nullable<int> Order_2 { get; set; }
        public Nullable<int> Inv { get; set; }
        public string OrderType_T { get; set; }
        public Nullable<short> OrderRelease { get; set; }
        public string PrintStatus_T { get; set; }
        public Nullable<short> CostedStatus { get; set; }
        public Nullable<short> OnHold { get; set; }
        public Nullable<int> Posting { get; set; }
        public Nullable<short> InventoryUpdated { get; set; }
        public Nullable<short> OrderComplete { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public Nullable<System.DateTime> ExpectedShipDate { get; set; }
        public string ShipVia { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public Nullable<short> Loc { get; set; }
        public string CreditApprovalPerson { get; set; }
        public string FOBPoint { get; set; }
        public string TaxGroup { get; set; }
        public Nullable<float> TotalOrderValueHome { get; set; }
        public Nullable<short> LinesinOrder { get; set; }
        public Nullable<short> InvDisc { get; set; }
        public string Reference { get; set; }
        public string Contact { get; set; }
        public string TaxExempt1 { get; set; }
        public string TaxExempt2 { get; set; }
        public string Terms { get; set; }
        public Nullable<short> Salesperson { get; set; }
        public Nullable<short> CustTaxStatus { get; set; }
        public string PreAR90Territory { get; set; }
        public string CustDiscLevel { get; set; }
        public string Name { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingAddress3 { get; set; }
        public string BillingAddress4 { get; set; }
        public string BillingZipPostal { get; set; }
        public Nullable<short> ShipName { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipAddress3 { get; set; }
        public string ShipAddress4 { get; set; }
        public string ShipZipPostal { get; set; }
        public string LabelsCount { get; set; }
        public Nullable<short> GLPosting { get; set; }
        public Nullable<short> ARPosting { get; set; }
        public Nullable<short> TermsCode { get; set; }
        public string Bank { get; set; }
        public string CashAcct { get; set; }
        public Nullable<short> CashDept { get; set; }
        public string Cheque { get; set; }
        public string DateDue { get; set; }
        public Nullable<System.DateTime> DateDisc { get; set; }
        public Nullable<System.DateTime> TermsDisc { get; set; }
        public Nullable<short> SourceDecimals { get; set; }
        public Nullable<short> HomeCurr { get; set; }
        public string RateType { get; set; }
        public string SourceCurr { get; set; }
        public string RateDate { get; set; }
        public Nullable<System.DateTime> ExchgRate { get; set; }
        public Nullable<short> ExchgSpread { get; set; }
        public Nullable<short> RateRep { get; set; }
        public string DateMatching { get; set; }
        public string BillingTelephone { get; set; }
        public string BillingFax { get; set; }
        public Nullable<long> ShipTelephone { get; set; }
        public string ShipFax { get; set; }
        public string PriceList { get; set; }
        public string CashDisc { get; set; }
        public Nullable<short> ForeignHomeCurr { get; set; }
        public string ForeignRateType { get; set; }
        public string ForeignSourceCurr { get; set; }
        public string ForeignRateDate { get; set; }
        public Nullable<System.DateTime> ForeignRate { get; set; }
        public Nullable<short> ForeignSpread { get; set; }
        public Nullable<short> ForeignRateRep { get; set; }
        public string ForeignDateMatching { get; set; }
        public string RateOverride { get; set; }
        public Nullable<short> ForeignRateOverride { get; set; }
        public Nullable<short> ForeignDecimals { get; set; }
        public Nullable<short> DiscAcct { get; set; }
        public Nullable<short> DiscDept { get; set; }
        public string RoundAcct { get; set; }
        public string RoundDept { get; set; }
        public string TaxByInv { get; set; }
        public Nullable<short> TotalOrderValue { get; set; }
        public Nullable<float> TotalDollarValue { get; set; }
        public Nullable<float> InvDiscAmt { get; set; }
        public Nullable<short> Tax1 { get; set; }
        public Nullable<float> Tax2 { get; set; }
        public Nullable<float> Tax3 { get; set; }
        public Nullable<float> Tax4 { get; set; }
        public Nullable<short> Tax5 { get; set; }
        public Nullable<short> TotalCostValue { get; set; }
        public Nullable<float> CashPayment { get; set; }
        public Nullable<short> DiscBase { get; set; }
        public Nullable<float> ForeignAmt { get; set; }
        public Nullable<short> MovedtoHistory { get; set; }
        public Nullable<short> RNumAO80AHED { get; set; }
    }
}