//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdagioItemsImport
    {
        public string Item { get; set; }
        public string SetKey { get; set; }
        public string Item2 { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public string ReportGroup { get; set; }
        public string StockItem { get; set; }
        public string ItemsUsedinBOMCount { get; set; }
        public string SerialCount { get; set; }
        public string LayawayCounter { get; set; }
        public string Unit { get; set; }
        public string AltUnit1 { get; set; }
        public string AltUnit2 { get; set; }
        public string AltUnit3 { get; set; }
        public string AltUnit4 { get; set; }
        public string PurchaseUnit { get; set; }
        public string PriceUnit { get; set; }
        public string AltFactor1 { get; set; }
        public string AltFactor2 { get; set; }
        public string AltFactor3 { get; set; }
        public string AltFactor4 { get; set; }
        public string BasePrice { get; set; }
        public string PickingSeq { get; set; }
        public string StdCost { get; set; }
        public string UnitWeight { get; set; }
        public string SaleStartDate { get; set; }
        public string SaleEndDate { get; set; }
        public string SalePrice { get; set; }
        public string CtrlAcctSet { get; set; }
        public string TaxStatus { get; set; }
        public string UserDefinedCost1 { get; set; }
        public string UserDefinedCost2 { get; set; }
        public string DiscType_T { get; set; }
        public string DiscFormat_T { get; set; }
        public string DiscBase_T { get; set; }
        public string DiscMarkupQty1 { get; set; }
        public string DiscMarkupQty2 { get; set; }
        public string DiscMarkupQty3 { get; set; }
        public string DiscMarkupQty4 { get; set; }
        public string DiscMarkupQty5 { get; set; }
        public string QtyonPO { get; set; }
        public string QtyonSO { get; set; }
        public string QtyTempCommitted { get; set; }
        public string QtyShippednotCost { get; set; }
        public string LastShipmentDate { get; set; }
        public string LastRcptDate { get; set; }
        public string MostRecentCost { get; set; }
        public string MarkupFactor { get; set; }
        public string PrevPriceChangeDate { get; set; }
        public string PrevPrice { get; set; }
        public string PrevStdCostDate { get; set; }
        public string PrevStdCost { get; set; }
        public string PrevRecentCostDate { get; set; }
        public string PrevRecentCost { get; set; }
        public string Rcpt1 { get; set; }
        public string Rcpt2 { get; set; }
        public string Rcpt3 { get; set; }
        public string Rcpt4 { get; set; }
        public string Rcpt5 { get; set; }
        public string RcptDate1 { get; set; }
        public string RcptDate2 { get; set; }
        public string RcptDate3 { get; set; }
        public string RcptDate4 { get; set; }
        public string RcptDate5 { get; set; }
        public string QtyonHand1 { get; set; }
        public string QtyonHand2 { get; set; }
        public string QtyonHand3 { get; set; }
        public string QtyonHand4 { get; set; }
        public string QtyonHand5 { get; set; }
        public string TotalCost1 { get; set; }
        public string TotalCost2 { get; set; }
        public string TotalCost3 { get; set; }
        public string TotalCost4 { get; set; }
        public string TotalCost5 { get; set; }
        public string AvgDaysBetweenShipments { get; set; }
        public string AvgUnitsShipped { get; set; }
        public string ShipmentCount { get; set; }
        public string UnitsSoldPeriod1 { get; set; }
        public string UnitsSoldPeriod2 { get; set; }
        public string UnitsSoldPeriod3 { get; set; }
        public string UnitsSoldPeriod4 { get; set; }
        public string UnitsSoldPeriod5 { get; set; }
        public string UnitsSoldPeriod6 { get; set; }
        public string UnitsSoldPeriod7 { get; set; }
        public string UnitsSoldPeriod8 { get; set; }
        public string UnitsSoldPeriod9 { get; set; }
        public string UnitsSoldPeriod10 { get; set; }
        public string UnitsSoldPeriod11 { get; set; }
        public string UnitsSoldPeriod12 { get; set; }
        public string UnitsSoldPeriod13 { get; set; }
        public string UnitsSoldYTD { get; set; }
        public string UnitsSoldLY { get; set; }
        public string AmtSoldPeriod1 { get; set; }
        public string AmtSoldPeriod2 { get; set; }
        public string AmtSoldPeriod3 { get; set; }
        public string AmtSoldPeriod4 { get; set; }
        public string AmtSoldPeriod5 { get; set; }
        public string AmtSoldPeriod6 { get; set; }
        public string AmtSoldPeriod7 { get; set; }
        public string AmtSoldPeriod8 { get; set; }
        public string AmtSoldPeriod9 { get; set; }
        public string AmtSoldPeriod10 { get; set; }
        public string AmtSoldPeriod11 { get; set; }
        public string AmtSoldPeriod12 { get; set; }
        public string AmtSoldPeriod13 { get; set; }
        public string AmtSoldYTD { get; set; }
        public string AmtSoldLY { get; set; }
        public string TotalCostsPeriod1 { get; set; }
        public string TotalCostsPeriod2 { get; set; }
        public string TotalCostsPeriod3 { get; set; }
        public string TotalCostsPeriod4 { get; set; }
        public string TotalCostsPeriod5 { get; set; }
        public string TotalCostsPeriod6 { get; set; }
        public string TotalCostsPeriod7 { get; set; }
        public string TotalCostsPeriod8 { get; set; }
        public string TotalCostsPeriod9 { get; set; }
        public string TotalCostsPeriod10 { get; set; }
        public string TotalCostsPeriod11 { get; set; }
        public string TotalCostsPeriod12 { get; set; }
        public string TotalCostsPeriod13 { get; set; }
        public string TotalCostsYTD { get; set; }
        public string TotalCostsLY { get; set; }
        public string UnitsLostYTD { get; set; }
        public string UnitsLostLY { get; set; }
        public string DiscDecimals { get; set; }
        public string DiscMarkupAmt1 { get; set; }
        public string DiscMarkupAmt2 { get; set; }
        public string DiscMarkupAmt3 { get; set; }
        public string DiscMarkupAmt4 { get; set; }
        public string DiscMarkupAmt5 { get; set; }
        public string QtyOnHand { get; set; }
        public string Selected { get; set; }
        public string ActiveItem { get; set; }
        public string RNumAN81CITM { get; set; }
        public int ID { get; set; }
    }
}
