//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_companies
    {
        public base_companies()
        {
            this.base_companies1 = new HashSet<base_companies>();
            this.proc_lots = new HashSet<proc_lots>();
            this.proc_lots1 = new HashSet<proc_lots>();
            this.proc_lots2 = new HashSet<proc_lots>();
            this.proc_lots3 = new HashSet<proc_lots>();
            this.proc_packs = new HashSet<proc_packs>();
        }
    
        public int company { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string shname { get; set; }
        public string extcode { get; set; }
        public string pattern { get; set; }
        public Nullable<int> dimension1 { get; set; }
        public Nullable<int> dimension2 { get; set; }
        public Nullable<int> dimension3 { get; set; }
        public Nullable<int> dimension4 { get; set; }
        public string description1 { get; set; }
        public string description2 { get; set; }
        public string description3 { get; set; }
        public string description4 { get; set; }
        public string description5 { get; set; }
        public string description6 { get; set; }
        public string description7 { get; set; }
        public string description8 { get; set; }
        public string xmldata { get; set; }
        public Nullable<int> itgrsite { get; set; }
        public string itgrstatus { get; set; }
        public bool active { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string postcode { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public Nullable<int> country { get; set; }
        public string telephone { get; set; }
        public string fax { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public Nullable<int> cultureid { get; set; }
        public bool issupplier { get; set; }
        public bool isowner { get; set; }
        public bool isproducer { get; set; }
        public bool isprocessor { get; set; }
        public bool isstorage { get; set; }
        public bool istransporter { get; set; }
        public bool isentryport { get; set; }
        public bool iscustomer { get; set; }
        public bool isagent { get; set; }
        public bool islicenseholder { get; set; }
        public Nullable<int> rmarea { get; set; }
        public Nullable<int> parent { get; set; }
        public string prlicense { get; set; }
        public byte[] prlogo { get; set; }
        public string pklicense { get; set; }
        public byte[] pklogo { get; set; }
        public string ssccprefix { get; set; }
    
        public virtual ICollection<base_companies> base_companies1 { get; set; }
        public virtual base_companies base_companies2 { get; set; }
        public virtual ICollection<proc_lots> proc_lots { get; set; }
        public virtual ICollection<proc_lots> proc_lots1 { get; set; }
        public virtual ICollection<proc_lots> proc_lots2 { get; set; }
        public virtual ICollection<proc_lots> proc_lots3 { get; set; }
        public virtual ICollection<proc_packs> proc_packs { get; set; }
    }
}
