//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class innova01Entities : DbContext
    {
        public innova01Entities()
            : base("name=innova01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<proc_sizes> proc_sizes { get; set; }
        public virtual DbSet<base_companies> base_companies { get; set; }
        public virtual DbSet<proc_lots> proc_lots { get; set; }
        public virtual DbSet<proc_materials> proc_materials { get; set; }
        public virtual DbSet<proc_packs> proc_packs { get; set; }
    }
}
