//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHeader
    {
        public string CustPrefix { get; set; }
        public Nullable<double> Cust { get; set; }
        public string OrderKey { get; set; }
        public string DocType_T { get; set; }
        public Nullable<double> Doc { get; set; }
        public Nullable<double> Order_2 { get; set; }
        public Nullable<double> Inv { get; set; }
        public string CN { get; set; }
        public string OrderType_T { get; set; }
        public Nullable<double> OrderRelease { get; set; }
        public string PrintStatus_T { get; set; }
        public Nullable<double> CostedStatus { get; set; }
        public Nullable<double> OnHold { get; set; }
        public Nullable<double> Posting { get; set; }
        public Nullable<double> InventoryUpdated { get; set; }
        public Nullable<double> OrderComplete { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string InvDate { get; set; }
        public string ShipmentDate { get; set; }
        public Nullable<System.DateTime> ExpectedShipDate { get; set; }
        public string ShipVia { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public Nullable<double> Loc { get; set; }
        public string CreditApprovalPerson { get; set; }
        public string FOBPoint { get; set; }
        public string TaxGroup { get; set; }
        public Nullable<double> TotalOrderValueHome { get; set; }
        public Nullable<double> LinesinOrder { get; set; }
        public Nullable<double> InvDisc { get; set; }
        public string Reference { get; set; }
        public string Contact { get; set; }
        public string TaxExempt1 { get; set; }
        public string TaxExempt2 { get; set; }
        public string Terms { get; set; }
        public Nullable<double> Salesperson { get; set; }
        public Nullable<double> CustTaxStatus { get; set; }
        public string PreAR90Territory { get; set; }
        public string CustDiscLevel { get; set; }
        public string Name { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingAddress3 { get; set; }
        public string BillingAddress4 { get; set; }
        public string BillingZipPostal { get; set; }
        public string Shipto { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipAddress3 { get; set; }
        public string ShipAddress4 { get; set; }
        public string ShipZipPostal { get; set; }
        public Nullable<double> LabelsCount { get; set; }
        public Nullable<double> GLPosting { get; set; }
        public Nullable<double> ARPosting { get; set; }
        public string TermsCode { get; set; }
        public string Bank { get; set; }
        public Nullable<double> CashAcct { get; set; }
        public string CashDept { get; set; }
        public string Cheque { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public string DateDisc { get; set; }
        public Nullable<double> TermsDisc { get; set; }
        public Nullable<double> SourceDecimals { get; set; }
        public string HomeCurr { get; set; }
        public string RateType { get; set; }
        public string SourceCurr { get; set; }
        public Nullable<System.DateTime> RateDate { get; set; }
        public Nullable<double> ExchgRate { get; set; }
        public Nullable<double> ExchgSpread { get; set; }
        public string RateRep { get; set; }
        public string DateMatching { get; set; }
        public string BillingTelephone { get; set; }
        public string BillingFax { get; set; }
        public string ShipTelephone { get; set; }
        public string ShipFax { get; set; }
        public string PriceList { get; set; }
        public Nullable<double> CashDisc { get; set; }
        public string ForeignHomeCurr { get; set; }
        public string ForeignRateType { get; set; }
        public string ForeignSourceCurr { get; set; }
        public Nullable<System.DateTime> ForeignRateDate { get; set; }
        public Nullable<double> ForeignRate { get; set; }
        public Nullable<double> ForeignSpread { get; set; }
        public string ForeignRateRep { get; set; }
        public string ForeignDateMatching { get; set; }
        public Nullable<double> RateOverride { get; set; }
        public Nullable<double> ForeignRateOverride { get; set; }
        public Nullable<double> ForeignDecimals { get; set; }
        public Nullable<double> DiscAcct { get; set; }
        public string DiscDept { get; set; }
        public string RoundAcct { get; set; }
        public string RoundDept { get; set; }
        public Nullable<double> TaxByInv { get; set; }
        public Nullable<double> TotalOrderValue { get; set; }
        public Nullable<double> TotalDollarValue { get; set; }
        public Nullable<double> InvDiscAmt { get; set; }
        public Nullable<double> Tax1 { get; set; }
        public Nullable<double> Tax2 { get; set; }
        public Nullable<double> Tax3 { get; set; }
        public Nullable<double> Tax4 { get; set; }
        public Nullable<double> Tax5 { get; set; }
        public Nullable<double> TotalCostValue { get; set; }
        public Nullable<double> CashPayment { get; set; }
        public Nullable<double> DiscBase { get; set; }
        public Nullable<double> ForeignAmt { get; set; }
        public Nullable<double> MovedtoHistory { get; set; }
        public string RNumAO80AHED { get; set; }
        public int ID { get; set; }
    }
}
