//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTransaction
    {
        public Nullable<double> Cust { get; set; }
        public string Shipto { get; set; }
        public string JulianDateKey { get; set; }
        public string HexUniquifer { get; set; }
        public string TransactionUnquifier { get; set; }
        public Nullable<double> Item { get; set; }
        public Nullable<double> ItemSegment1CATEGORY { get; set; }
        public Nullable<double> ItemSegment2ITEM { get; set; }
        public Nullable<double> ItemSegment3CTNWGT { get; set; }
        public Nullable<double> QIItem { get; set; }
        public string PrefixDocumentNumber { get; set; }
        public string Prefix { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<double> Uniquifier { get; set; }
        public string Type_T { get; set; }
        public Nullable<System.DateTime> Date_2 { get; set; }
        public Nullable<double> Salesperson { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Amt { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> BasePrice { get; set; }
        public Nullable<double> CustomerTaxStatus { get; set; }
        public Nullable<double> ItemTaxStatus { get; set; }
        public Nullable<double> Location { get; set; }
        public string Category { get; set; }
        public string Order_2 { get; set; }
        public string TaxGroup { get; set; }
        public string RecordSource_T { get; set; }
        public string ItemSource_T { get; set; }
        public string PriceList { get; set; }
        public string DiscountDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string DatePaid { get; set; }
        public string InvoicePaid_T { get; set; }
        public string Reference { get; set; }
        public string PONumber { get; set; }
        public string OrginalInvoice { get; set; }
        public Nullable<double> Line { get; set; }
        public string Territory { get; set; }
        public Nullable<double> Itemreportgroup { get; set; }
        public string Customerreportgroup { get; set; }
        public string ManualStyleCode { get; set; }
        public string AutomaticStyleCode { get; set; }
        public Nullable<double> SourceDecimals { get; set; }
        public string HomeCurr { get; set; }
        public string RateType { get; set; }
        public string SourceCurr { get; set; }
        public Nullable<System.DateTime> RateDate { get; set; }
        public Nullable<double> Rate { get; set; }
        public string RateRep { get; set; }
        public string DateMatching { get; set; }
        public Nullable<double> SourceAmt { get; set; }
        public Nullable<double> SourceCost { get; set; }
        public Nullable<double> SourceBasePrice { get; set; }
        public string LineItemDescription { get; set; }
        public string RNumAS90ATRN { get; set; }
        public int ID { get; set; }
    }
}
