//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StimulantStageEntities : DbContext
    {
        public StimulantStageEntities()
            : base("name=StimulantStageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderHeader> OrderHeaders { get; set; }
        public virtual DbSet<SalesTransaction> SalesTransactions { get; set; }
        public virtual DbSet<TodayOrder> TodayOrders { get; set; }
        public virtual DbSet<AdagioItem> AdagioItems { get; set; }
        public virtual DbSet<AdagioItemsImport> AdagioItemsImports { get; set; }
        public virtual DbSet<CustomersImport> CustomersImports { get; set; }
        public virtual DbSet<OrderHeadersImport> OrderHeadersImports { get; set; }
        public virtual DbSet<SalesTransactionsImport> SalesTransactionsImports { get; set; }
        public virtual DbSet<TodayOrdersImport> TodayOrdersImports { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<OrderDetailsImport> OrderDetailsImports { get; set; }
    }
}
