//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodayOrdersImport
    {
        public string CustPrefix { get; set; }
        public string Cust { get; set; }
        public string OrderKey { get; set; }
        public string DocType_T { get; set; }
        public string Doc { get; set; }
        public string Order_2 { get; set; }
        public string Inv { get; set; }
        public string CN { get; set; }
        public string OrderType_T { get; set; }
        public string OrderRelease { get; set; }
        public string PrintStatus_T { get; set; }
        public string CostedStatus { get; set; }
        public string OnHold { get; set; }
        public string Posting { get; set; }
        public string InventoryUpdated { get; set; }
        public string OrderComplete { get; set; }
        public string OrderDate { get; set; }
        public string InvDate { get; set; }
        public string ShipmentDate { get; set; }
        public string ExpectedShipDate { get; set; }
        public string ShipVia { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public string Loc { get; set; }
        public string CreditApprovalPerson { get; set; }
        public string FOBPoint { get; set; }
        public string TaxGroup { get; set; }
        public string TotalOrderValueHome { get; set; }
        public string LinesinOrder { get; set; }
        public string InvDisc { get; set; }
        public string Reference { get; set; }
        public string Contact { get; set; }
        public string TaxExempt1 { get; set; }
        public string TaxExempt2 { get; set; }
        public string Terms { get; set; }
        public string Salesperson { get; set; }
        public string CustTaxStatus { get; set; }
        public string PreAR90Territory { get; set; }
        public string CustDiscLevel { get; set; }
        public string Name { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingAddress3 { get; set; }
        public string BillingAddress4 { get; set; }
        public string BillingZipPostal { get; set; }
        public string Shipto { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipAddress3 { get; set; }
        public string ShipAddress4 { get; set; }
        public string ShipZipPostal { get; set; }
        public string LabelsCount { get; set; }
        public string GLPosting { get; set; }
        public string ARPosting { get; set; }
        public string TermsCode { get; set; }
        public string Bank { get; set; }
        public string CashAcct { get; set; }
        public string CashDept { get; set; }
        public string Cheque { get; set; }
        public string DateDue { get; set; }
        public string DateDisc { get; set; }
        public string TermsDisc { get; set; }
        public string SourceDecimals { get; set; }
        public string HomeCurr { get; set; }
        public string RateType { get; set; }
        public string SourceCurr { get; set; }
        public string RateDate { get; set; }
        public string ExchgRate { get; set; }
        public string ExchgSpread { get; set; }
        public string RateRep { get; set; }
        public string DateMatching { get; set; }
        public string BillingTelephone { get; set; }
        public string BillingFax { get; set; }
        public string ShipTelephone { get; set; }
        public string ShipFax { get; set; }
        public string PriceList { get; set; }
        public string CashDisc { get; set; }
        public string ForeignHomeCurr { get; set; }
        public string ForeignRateType { get; set; }
        public string ForeignSourceCurr { get; set; }
        public string ForeignRateDate { get; set; }
        public string ForeignRate { get; set; }
        public string ForeignSpread { get; set; }
        public string ForeignRateRep { get; set; }
        public string ForeignDateMatching { get; set; }
        public string RateOverride { get; set; }
        public string ForeignRateOverride { get; set; }
        public string ForeignDecimals { get; set; }
        public string DiscAcct { get; set; }
        public string DiscDept { get; set; }
        public string RoundAcct { get; set; }
        public string RoundDept { get; set; }
        public string TaxByInv { get; set; }
        public string TotalOrderValue { get; set; }
        public string TotalDollarValue { get; set; }
        public string InvDiscAmt { get; set; }
        public string Tax1 { get; set; }
        public string Tax2 { get; set; }
        public string Tax3 { get; set; }
        public string Tax4 { get; set; }
        public string Tax5 { get; set; }
        public string TotalCostValue { get; set; }
        public string CashPayment { get; set; }
        public string DiscBase { get; set; }
        public string ForeignAmt { get; set; }
        public string MovedtoHistory { get; set; }
        public string RNumAO80AHED { get; set; }
        public int ID { get; set; }
    }
}
