//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBOL2
    {
        public string OrderCode { get; set; }
        public Nullable<int> CustNumber { get; set; }
        public string CustShort { get; set; }
        public string CustLong { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public int MaterialID { get; set; }
        public string PM_Name43 { get; set; }
        public Nullable<float> OrderedAmt { get; set; }
        public Nullable<int> UnitCount { get; set; }
        public Nullable<float> NewShippedAmt { get; set; }
        public Nullable<float> ExtendedTotalWt { get; set; }
        public string HowPacked { get; set; }
        public string WeightLabel { get; set; }
    }
}
