//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBOLProd
    {
        public string OrderCode { get; set; }
        public Nullable<int> CustNumber { get; set; }
        public string CustShort { get; set; }
        public string CustLong { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DispDate { get; set; }
        public string PO1 { get; set; }
        public string PO2 { get; set; }
        public string PO3 { get; set; }
        public string Comments { get; set; }
        public string OrderTerms { get; set; }
        public string ShipToName { get; set; }
        public string ShipToAddress { get; set; }
        public string ShipToPhone { get; set; }
        public int MaterialID { get; set; }
        public string ProdCode { get; set; }
        public string ProdName { get; set; }
        public Nullable<float> OrderedAmt { get; set; }
        public Nullable<int> ShippedQty { get; set; }
        public float ShippedWeight { get; set; }
        public double ApproxUnitWeight { get; set; }
        public string HowPacked { get; set; }
        public string WeightLabel { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerAddress2 { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerState { get; set; }
        public string CustomerZip { get; set; }
        public string CustomerPhone { get; set; }
        public string Terms { get; set; }
    }
}
